# Generated by Django 3.0.3 on 2021-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.TextField(default='None'),
        ),
    ]
