# Generated by Django 3.0.3 on 2021-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20210321_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.TextField(null=True),
        ),
    ]
