# Generated by Django 3.0.3 on 2021-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.TextField(default=''),
        ),
    ]
