# Generated by Django 3.0.3 on 2021-04-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_playlist_description'),
        ('mainsite', '0007_song_album'),
    ]

    operations = [
    ]
