# Generated by Django 3.0.3 on 2021-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20210401_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='song_artists', to='mainsite.Artist'),
        ),
    ]
